[global]
target = "~/.local/bin"
upgrade_only = true

["ClementTsang/bottom"]
asset_filters = ["musl"]
file = "btm"
target = "~/.local/bin/btm"
["It4innovations/hyperqueue"]
asset_filters = ["hq"]
target = "~/.local/bin/hq"
["NixOS/patchelf"]
asset_filters = ["x86_64"]
["astral-sh/uv"]
asset_filters = ["musl"]
["bootandy/dust"]
asset_filters = ["musl"]
["carapace-sh/carapace-bin"]
asset_filters = ["tar"]
file = "carapace"
target = "~/.local/bin/carapace"
["chmln/sd"]
asset_filters = ["musl"]
["cli/cli"]
asset_filters = ["tar"]
target = "~/.local/bin/gh"
["dandavison/delta"]
asset_filters = ["musl"]
["eza-community/eza"]
asset_filters = ["musl.tar"]
["jqlang/jq"]
asset_filters = ["amd64"]
["koalaman/shellcheck"]
asset_filters = ["gz"]
["muesli/duf"]
asset_filters = ["tar"]
["prefix-dev/pixi"]
asset_filters = ["tar"]
["sharkdp/bat"]
asset_filters = ["musl.tar"]
["sharkdp/fd"]
asset_filters = ["musl"]
["sharkdp/hyperfine"]
asset_filters = ["musl"]
["starship/starship"]
asset_filters = ["musl"]
["tealdeer-rs/tealdeer"]
target = "~/.local/bin/tldr"
["watchexec/watchexec"]
asset_filters = ["musl", "tar", "^.b3", "^.sha"]
["zellij-org/zellij"]
asset_filters = ["zellij-x86_64"]
["zyedidia/micro"]
asset_filters = ["static", "^.sha"]
