[git.variables]
"gh-binary" = "/home/chen1plus/.local/bin/gh"

[sc.variables]
"eget-packages" = "/home/chen1plus/dotfiles/sc/eget.packages"
"eget-pkg-completions" = "/home/chen1plus/dotfiles/sc/eget.pkg.completions"

[zellij.variables]
"micro-binary" = "/home/chen1plus/.local/bin/micro"
