[bash]
"depends" = ["sc"]
[bash.files]
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.bash_profile"
"bash/starship.toml" = "~/.config/starship.toml"

[dms.files]
"dms/clsettings.json" = "~/.config/DankMaterialShell/clsettings.json"
"dms/plugin_settings.json" = "~/.config/DankMaterialShell/plugin_settings.json"
"dms/settings.json" = "~/.config/DankMaterialShell/settings.json"

[fastfetch.files]
"fastfetch/config.jsonc" = "~/.config/fastfetch/config.jsonc"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/greeting.fish" = "~/.config/fish/functions/fish_greeting.fish"

[ghostty.files]
"ghostty/config" = "~/.config/ghostty/config"

[git.files]
"git/config" = "~/.config/git/config"

[niri.files]
"niri/config.kdl" = "~/.config/niri/config.kdl"
"niri/tuf/apps.kdl" = "~/.config/niri/tuf/apps.kdl"
"niri/tuf/binds.kdl" = "~/.config/niri/tuf/binds.kdl"
"niri/tuf/device.kdl" = "~/.config/niri/tuf/device.kdl"
"niri/tuf/layout.kdl" = "~/.config/niri/tuf/layout.kdl"

[sc.files]
"sc/eget.toml" = "~/.eget.toml"
"sc/eget-update" = "~/.local/bin/eget-update"

[zed.files]
"zed/keymap.json" = "~/.config/zed/keymap.json"
"zed/settings.json" = "~/.config/zed/settings.json"

[zellij.files]
"zellij/config.kdl" = "~/.config/zellij/config.kdl"
