[bash.files]
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.bash_profile"
"bash/starship.toml" = "~/.config/starship.toml"

[git.files]
"git/config" = "~/.config/git/config"

[zellij.files]
"zellij/config.kdl" = "~/.config/zellij/config.kdl"
