[bash]
"depends" = ["sc"]
[bash.files]
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.bash_profile"
"bash/starship.toml" = "~/.config/starship.toml"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/greeting.fish" = "~/.config/fish/functions/fish_greeting.fish"

[ghostty.files]
"ghostty/config" = "~/.config/ghostty/config"

[git.files]
"git/config" = "~/.config/git/config"

[sc.files]
"sc/eget.toml" = "~/.eget.toml"
"sc/eget-update" = "~/.local/bin/eget-update"

[zed.files]
"zed/keymap.json" = "~/.config/zed/keymap.json"
"zed/settings.json" = "~/.config/zed/settings.json"

[zellij.files]
"zellij/config.kdl" = "~/.config/zellij/config.kdl"
